package it.telemedicina.backend.domain;

public enum FattoriRischio {
    FUMO,
    CONSUMO_ECCESSIVO_DI_ALCOOL,
    INATTIVITA_FISICA,
    DIETA_SBILANCIATA,
    SCARSA_ADESIONE_ALLA_TERAPIA,
    STRESS_CRONICO,
    SCARSO_CONTROLLO_GLICEMICO,
    MANCATA_AUTOMONITORAGGIO,
    PRIVAZIONE_DEL_SONNO,
    ECCESSO_DI_PESO
}
